---
apiVersion: v1
kind: Service
metadata:
  name: argonaut-simple-bluegreen-service
spec:
  type: LoadBalancer
  selector:
    app: argonaut-simple-bluegreen
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
