---
kind: Service
apiVersion: v1
metadata:
  name: argonaut-rollout-bluegreen-active
spec:
  selector:
    app: argonaut-rollout-bluegreen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: argonaut-rollout-bluegreen-preview
spec:
  selector:
    app: argonaut-rollout-bluegreen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
